[11:25 p.m., 1/6/2026] Abraham Anaya: =====================================================================
[11:28 p.m., 1/6/2026] Abraham Anaya: name: Compilar Binarios
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Instalar dependencias
        run: pip install pyinstaller customtkinter ccxt pandas pandas_ta matplotlib cryptography
      - name: Compilar
        run: pyinstaller --onefile synapse_free_core.py
      - name: Subir binario
        uses: actions/upload-artifact@v3
        with:
          name: Synapse-Win
          path: dist/
